### ISSUE TITLE
Issue with Forge docker container

### ISSUE THREAD

**Issue by NSmeef** [nathandines/forge#54]
Looks like CA certs needs to be added to the docker image? Or am I doing something wrong?

    2018/06/12 04:53:42 RequestError: send request failed
    caused by: Post https://cloudformation.eu-west-2.amazonaws.com/: x509: failed to load system 
    roots and no roots provided

**Comment by nathandines** [comment]
Hey, as discussed out-of-band, issue appeared to be due to an environment specific dependency. Closing this issue.

**Comment by pkdcloud** [comment]
A quick fix if using Nathan's docker image, add this step to your circleci config after the checkout stage if it happens again.

`      - run:
          name: Update ca-certificates
          command: |
            apk update && apk upgrade && apk add --no-cache ca-certificates && update-ca-certificates 2>/dev/null || true `

Great tool by the way Nathan.

**Comment by nathandines** [comment]
So turns out the issue actually was present in multiple environments. I've adjusted the `Dockerfile` and re-pushed all of the images to Docker Hub with the change

**Comment by nsmeef** [comment]
Thanks, Nathan. 👍
